// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_welcome_to_the_surviving_jackhammer = "CgkIqr7ArMMbEAIQAw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIqr7ArMMbEAIQAQ"; // <GPGSID>
        public const string achievement_style_2 = "CgkIqr7ArMMbEAIQBA"; // <GPGSID>
        public const string achievement_style_3 = "CgkIqr7ArMMbEAIQBQ"; // <GPGSID>
        public const string achievement_style_4 = "CgkIqr7ArMMbEAIQBg"; // <GPGSID>
        public const string achievement_style_5 = "CgkIqr7ArMMbEAIQBw"; // <GPGSID>
        public const string achievement_music_2 = "CgkIqr7ArMMbEAIQCA"; // <GPGSID>
        public const string achievement_music_3 = "CgkIqr7ArMMbEAIQCQ"; // <GPGSID>
        public const string achievement_music_4 = "CgkIqr7ArMMbEAIQCg"; // <GPGSID>
        public const string achievement_music_5 = "CgkIqr7ArMMbEAIQCw"; // <GPGSID>

}

